import { test, expect } from '@playwright/test';
import process from 'node:process';
import type { Snapshot } from '../../lib/kitchen/client';

test('create an ingredient and recipe, resolve stale edits, and retain a draft through relocking', async ({ page, request }) => {
  const key = process.env.KITCHEN_TEST_TOKEN;
  if (!key) throw new Error('The isolated test runner must supply a temporary key.');
  await page.goto('/');
  await page.getByLabel('Private kitchen key').fill(key);
  await page.getByRole('button', { name: 'Unlock my kitchen' }).click();
  await expect(page.getByRole('heading', { name: 'What sounds good?' })).toBeVisible();
  await page.getByRole('button', { name: 'All recipes', exact: true }).click();
  await page.getByRole('button', { name: 'Add a recipe', exact: true }).click();
  await page.getByLabel('Recipe title', { exact: true }).fill('A browser-created recipe');
  const creator = page.getByRole('button', { name: 'Add an ingredient to your catalogue', exact: true });
  if ((await creator.getAttribute('aria-expanded')) !== 'true') await creator.click();
  await expect(creator).toHaveAttribute('aria-expanded', 'true');
  await page.getByLabel('New ingredient name', { exact: true }).fill('Test quinoa');
  await page.getByRole('button', { name: 'Create ingredient', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Added Test quinoa' })).toBeVisible();
  await page.getByLabel('Main ingredient', { exact: true }).selectOption('test-quinoa');
  await page.getByLabel('Ingredient 1', { exact: true }).selectOption('test-quinoa');
  await page.getByLabel('Quantity 1', { exact: true }).fill('150');
  await page.getByLabel('Preparation 1', { exact: true }).fill('Test-only ingredient record');
  await page.getByLabel('Step 1 instructions', { exact: true }).fill('This is an automated-test draft, not a recipe to cook.');
  await page.getByRole('button', { name: 'Save new recipe', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A browser-created recipe' })).toBeVisible();
  const id = new URL(page.url()).hash.split('/')[1];
  if (!id) throw new Error('Recipe was not assigned an ID.');
  await page.getByRole('button', { name: 'Edit recipe', exact: true }).click();
  await page.getByLabel('Recipe title', { exact: true }).fill('My unsaved change');
  const current = await request.get(`/api/recipes/${id}`, { headers: { Authorization: `Bearer ${key}` } });
  const envelope = await current.json() as { data: Snapshot };
  const tag = current.headers().etag;
  if (!tag) throw new Error('The recipe endpoint did not return an ETag.');
  const changed = await request.put(`/api/recipes/${id}`, { headers: { Authorization: `Bearer ${key}`, 'If-Match': tag }, data: { ...envelope.data.recipe, title: 'Changed elsewhere' } });
  expect(changed.status()).toBe(200);
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'changed in another tab' })).toBeVisible();
  await expect(page.getByLabel('Recipe title', { exact: true })).toHaveValue('My unsaved change');
  await page.getByRole('button', { name: 'Reload latest recipe', exact: true }).click();
  await page.getByRole('alertdialog').getByRole('button', { name: 'Discard and reload', exact: true }).click();
  await expect(page.getByLabel('Recipe title', { exact: true })).toHaveValue('Changed elsewhere');
  await page.getByLabel('Recipe title', { exact: true }).fill('Keep this through expiry');
  const revoked = await page.request.delete('/api/session', { headers: { Origin: 'http://127.0.0.1:8787', 'X-Kitchen-Request': '1' } });
  expect(revoked.status()).toBe(204);
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.getByLabel('Private kitchen key').fill(key);
  await page.getByRole('button', { name: 'Unlock my kitchen' }).click();
  await expect(page.getByLabel('Recipe title', { exact: true })).toHaveValue('Keep this through expiry');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Keep this through expiry' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Keep this through expiry' })).toBeVisible();
  await page.screenshot({ path: 'test-results/kitchen-recipe-detail.png', fullPage: true });
});
