-- Generated by pinned Drizzle Kit; IF NOT EXISTS also accepts the original PR #5 preview table.
CREATE TABLE IF NOT EXISTS `kitchen_remixes` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`target_id` text NOT NULL,
	`source_revision` integer NOT NULL,
	`target_revision` integer NOT NULL,
	`axis` text NOT NULL,
	`revision` integer DEFAULT 1 NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
	FOREIGN KEY (`source_id`,`source_revision`) REFERENCES `kitchen_recipe_history`(`recipeId`,`revision`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`target_id`,`target_revision`) REFERENCES `kitchen_recipe_history`(`recipeId`,`revision`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "remix_axis" CHECK("kitchen_remixes"."axis" IN ('main','flavor','method')),
	CONSTRAINT "remix_revision" CHECK("kitchen_remixes"."revision" > 0),
	CONSTRAINT "remix_canonical_pair" CHECK("kitchen_remixes"."source_id" < "kitchen_remixes"."target_id")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `kitchen_remixes_target` ON `kitchen_remixes` (`target_id`);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `kitchen_remixes_pair` ON `kitchen_remixes` (`source_id`,`target_id`);